version: '3.8'

services:
  # Service 1: The Streamlit Frontend
  streamlit-app:
    build: .
    container_name: iris-frontend
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0
    networks:
      - iris-network

  # Service 2: The FastAPI Backend
  fastapi-server:
    build: .
    container_name: iris-backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn api:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - iris-network

networks:
  iris-network:
    driver: bridge
